<a href="https://colab.research.google.com/github/Mrsenjiii/preprocessing_in_ml/blob/main/w1_l3_prepocessing_lec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preprocessing


1.   Handeling missing values
2.   Handeling Errors in Data
3.   Applying transformation
4.   Scaling of Data.
5.   Finding outliers in the data.
6.   seprating the features and labels



In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
data = pd.read_csv(data_url, sep=";")

In [ ]:
pdata = data.copy()
pdata=pd.DataFrame(pdata)
pdata.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

###How to remove a column ?

In [ ]:
# newdata = pdata.drop(columns=['residual sugar'] , inplace=True)
wine_features = pdata.drop("quality", axis=1)
wine_labels =  pdata['quality'].copy()

### Check for NA

In [ ]:
wine_features.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
dtype: int64

In [ ]:
wine_features

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [ ]:
wine_features.median()

fixed acidity            7.90000
volatile acidity         0.52000
citric acid              0.26000
residual sugar           2.20000
chlorides                0.07900
free sulfur dioxide     14.00000
total sulfur dioxide    38.00000
density                  0.99675
pH                       3.31000
sulphates                0.62000
alcohol                 10.20000
dtype: float64

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy='median')
imputer.fit(wine_features)
imputer.statistics_

array([ 7.9    ,  0.52   ,  0.26   ,  2.2    ,  0.079  , 14.     ,
       38.     ,  0.99675,  3.31   ,  0.62   , 10.2    ])

In [ ]:
nwf= imputer.transform(wine_features)

In [ ]:
nwf=pd.DataFrame(nwf,columns=wine_features.columns)

### Dealing with text data like category
<h1> One hot encoding </h1>


In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Create a sample DataFrame with multiple columns
data = {
    'Color': ['Red', 'Green', 'Blue', 'Green', 'Red'],
    'Size': ['Small', 'Large', 'Medium', 'Medium', 'Small'],
    'Shape': ['Circle', 'Rectangle', 'Triangle', 'Circle', 'Triangle']
}

df = pd.DataFrame(data)

# Initialize the OneHotEncoder
encoder = OneHotEncoder()

# Fit and transform the encoder to the 'Color' column
encoded_data = encoder.fit_transform(df[['Color']])
print(encoded_data.toarray() , encoder.get_feature_names_out(['Color']))
# Convert the sparse matrix to a dense DataFrame
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['Color']))

# Merge the one-hot encoded DataFrame with the original DataFrame
merged_df = pd.concat([df, encoded_df], axis=1)

# Display the merged DataFrame
print("Original DataFrame:")
print(df)
print("\nMerged DataFrame with One-Hot Encoding:")
print(merged_df)


[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] ['Color_Blue' 'Color_Green' 'Color_Red']
Original DataFrame:
   Color    Size      Shape
0    Red   Small     Circle
1  Green   Large  Rectangle
2   Blue  Medium   Triangle
3  Green  Medium     Circle
4    Red   Small   Triangle

Merged DataFrame with One-Hot Encoding:
   Color    Size      Shape  Color_Blue  Color_Green  Color_Red
0    Red   Small     Circle         0.0          0.0        1.0
1  Green   Large  Rectangle         0.0          1.0        0.0
2   Blue  Medium   Triangle         1.0          0.0        0.0
3  Green  Medium     Circle         0.0          1.0        0.0
4    Red   Small   Triangle         0.0          0.0        1.0


##Standard Scalar Standardization.



<div style="text-align:center">
<h1>
$\frac{x - \mu}{\sigma}$
</h1>

</div>


In [ ]:
from sklearn import preprocessing

In [ ]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
# scaler
# $x - \frac{\mu}{\sigma}$

# scaler.mean_

# scaler.scale_

X_scaled = scaler.transform(X_train)
X_scaled.mean(axis=0)
X_scaled.std(axis=0)

array([1., 1., 1.])

#MIn Max Scalar   
#Normalization


<h1 "style=text-align:center">

$ X_{\text{scaled}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}} $
</h1>

In [ ]:
minmax_scale = preprocessing.MinMaxScaler()
# fit(X_train)
scaled_minmax=minmax_scale.fit_transform(X_train)


In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
# fit(X_train)
scaled_minmax=min_max_scaler.fit_transform(X_train)
scaled_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [ ]:
X_test = np.array([[50,10,200]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[25. ,  5.5, 67. ]])

##Transformation pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [ ]:
transform_pipeline=Pipeline(
    [
      ('imputer' , SimpleImputer(strategy='median')),
      ('std_scalar' , StandardScaler())])

In [ ]:
tr_wine_features = transform_pipeline.fit_transform(wine_features)

In [ ]:
new_data  = pd.DataFrame(tr_wine_features, columns=wine_features.columns)

In [ ]:
new_data.describe()

fixed acidity  volatile acidity   citric acid  residual sugar  \
count   1.599000e+03      1.599000e+03  1.599000e+03    1.599000e+03   
mean    3.554936e-16      1.733031e-16 -8.887339e-17   -1.244227e-16   
std     1.000313e+00      1.000313e+00  1.000313e+00    1.000313e+00   
min    -2.137045e+00     -2.278280e+00 -1.391472e+00   -1.162696e+00   
25%    -7.007187e-01     -7.699311e-01 -9.293181e-01   -4.532184e-01   
50%    -2.410944e-01     -4.368911e-02 -5.636026e-02   -2.403750e-01   
75%     5.057952e-01      6.266881e-01  7.652471e-01    4.341614e-02   
max     4.355149e+00      5.877976e+00  3.743574e+00    9.195681e+00   

          chlorides  free sulfur dioxide  total sulfur dioxide       density  \
count  1.599000e+03         1.599000e+03          1.599000e+03  1.599000e+03   
mean   3.732682e-16        -6.221137e-17          4.443669e-17 -3.473172e-14   
std    1.000313e+00         1.000313e+00          1.000313e+00  1.000313e+00   
min   -1.603945e+00        -1.422500e+00         -1.230584e+00 -3.538731e+00   
25%   -3.712290e-01        -8.487156e-01         -7.440403e-01 -6.077557e-01   
50%   -1.799455e-01        -1.793002e-01         -2.574968e-01  1.760083e-03   
75%    5.384542e-02         4.901152e-01          4.723184e-01  5.768249e-01   
max    1.112703e+01         5.367284e+00          7.375154e+00  3.680055e+00   

                 pH     sulphates       alcohol  
count  1.599000e+03  1.599000e+03  1.599000e+03  
mean   2.861723e-15  6.754377e-16  1.066481e-16  
std    1.000313e+00  1.000313e+00  1.000313e+00  
min   -3.700401e+00 -1.936507e+00 -1.898919e+00  
25%   -6.551405e-01 -6.382196e-01 -8.663789e-01  
50%   -7.212705e-03 -2.251281e-01 -2.093081e-01  
75%    5.759223e-01  4.240158e-01  6.354971e-01  
max    4.528282e+00  7.918677e+00  4.202453e+00

In [ ]:
wine_features.describe(

)

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol  
count  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983  
std       0.154386     0.169507     1.065668  
min       2.740000     0.330000     8.400000  
25%       3.210000     0.550000     9.500000  
50%       3.310000     0.620000    10.200000  
75%       3.400000     0.730000    11.100000  
max       4.010000     2.000000    14.900000

In [ ]:
from sklearn.compose import ColumnTransformer